import os
import signal
import json
import logging
from datetime import datetime
from pathlib import Path
from flask import Flask, request, jsonify

app = Flask(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

# ── Config from env ────────────────────────────────────────────────────────────
TOKEN          = os.environ["DDNS_TOKEN"]
NGINX_CONF_DIR = os.environ.get("NGINX_CONF_DIR", "/etc/nginx/ddns")
STATE_FILE     = os.environ.get("STATE_FILE", "/data/state.json")

NGINX_PID_FILES = [
    "/run/nginx/nginx.pid",
    "/run/nginx.pid",
    "/var/run/nginx.pid",
]

# ── State ──────────────────────────────────────────────────────────────────────
def load_state() -> dict:
    try:
        return json.loads(Path(STATE_FILE).read_text())
    except Exception:
        return {}

def save_state(state: dict):
    Path(STATE_FILE).parent.mkdir(parents=True, exist_ok=True)
    Path(STATE_FILE).write_text(json.dumps(state, indent=2))

# ── Nginx ──────────────────────────────────────────────────────────────────────
def write_upstream(node: str, ip: str):
    Path(NGINX_CONF_DIR).mkdir(parents=True, exist_ok=True)
    conf_path = Path(NGINX_CONF_DIR) / f"{node}_ip.conf"
    content = (
        f"# Auto-generated by ddns | node={node} | updated={datetime.utcnow().isoformat()}Z\n"
        f"set ${node}_ip {ip};\n"
    )
    conf_path.write_text(content)
    log.info(f"Wrote {conf_path}")

def reload_nginx() -> tuple[bool, str]:
    # Find nginx PID
    pid = None
    for pid_file in NGINX_PID_FILES:
        try:
            content = Path(pid_file).read_text().strip()
            if content:
                pid = int(content)
                log.info(f"Found nginx pid={pid} in {pid_file}")
                break
        except Exception:
            continue

    if not pid:
        err = f"cannot find nginx pid in {NGINX_PID_FILES}"
        log.error(err)
        return False, err

    try:
        os.kill(pid, signal.SIGHUP)
        log.info(f"Sent SIGHUP to nginx pid={pid}")
        return True, "ok"
    except Exception as e:
        err = str(e)
        log.error(f"kill SIGHUP failed: {err}")
        return False, err

# ── Auth ───────────────────────────────────────────────────────────────────────
def authorized(req) -> bool:
    auth = req.headers.get("Authorization", "")
    if auth.startswith("Bearer "):
        return auth[7:] == TOKEN
    if req.is_json and req.json.get("token") == TOKEN:
        return True
    if req.args.get("token") == TOKEN:
        return True
    return False

def get_client_ip(req) -> str:
    for header in ("CF-Connecting-IP", "X-Real-IP", "X-Forwarded-For"):
        val = req.headers.get(header)
        if val:
            return val.split(",")[0].strip()
    return req.remote_addr

# ── Routes ─────────────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return jsonify({"status": "ok", "time": datetime.utcnow().isoformat() + "Z"})


@app.post("/update")
def update():
    if not authorized(request):
        log.warning(f"Unauthorized request from {request.remote_addr}")
        return jsonify({"error": "unauthorized"}), 401

    data = request.get_json(silent=True) or {}

    node = data.get("node", "").strip()
    if not node or not node.replace("-", "").replace("_", "").isalnum():
        return jsonify({"error": "node name required (alphanumeric, hyphens, underscores)"}), 400

    ip = data.get("ip") or get_client_ip(request)
    port = int(data.get("port", 80))

    state = load_state()
    old_ip = state.get(node, {}).get("ip")

    state[node] = {
        "ip":      ip,
        "port":    port,
        "updated": datetime.utcnow().isoformat() + "Z",
    }

    write_upstream(node, ip)
    save_state(state)

    ok, msg = reload_nginx()
    if not ok:
        return jsonify({
            "error":  "nginx reload failed",
            "detail": msg,
            "node":   node,
            "ip":     ip,
        }), 500

    log.info(f"Updated node={node} ip={ip} port={port} (was {old_ip})")
    return jsonify({
        "status":  "ok",
        "node":    node,
        "ip":      ip,
        "port":    port,
        "changed": old_ip != ip,
        "old_ip":  old_ip,
    })


@app.get("/status")
def status():
    if not authorized(request):
        return jsonify({"error": "unauthorized"}), 401
    return jsonify(load_state())


@app.delete("/node/<node>")
def delete_node(node: str):
    if not authorized(request):
        return jsonify({"error": "unauthorized"}), 401

    state = load_state()
    if node not in state:
        return jsonify({"error": "node not found"}), 404

    conf_path = Path(NGINX_CONF_DIR) / f"{node}_ip.conf"
    conf_path.unlink(missing_ok=True)

    del state[node]
    save_state(state)

    ok, msg = reload_nginx()
    if not ok:
        return jsonify({"error": "nginx reload failed", "detail": msg}), 500

    return jsonify({"status": "ok", "deleted": node})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=False)
