import os
import json
import subprocess
import logging
from datetime import datetime
from pathlib import Path
from flask import Flask, request, jsonify

app = Flask(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

# ── Config from env ────────────────────────────────────────────────────────────
TOKEN          = os.environ["DDNS_TOKEN"]           # required, no default
NGINX_CONF_DIR = os.environ.get("NGINX_CONF_DIR", "/etc/nginx/conf.d")
NGINX_RELOAD   = os.environ.get("NGINX_RELOAD_CMD", "nginx -s reload")
STATE_FILE     = os.environ.get("STATE_FILE", "/data/state.json")

# ── State (persisted to disk) ──────────────────────────────────────────────────
def load_state() -> dict:
    try:
        return json.loads(Path(STATE_FILE).read_text())
    except Exception:
        return {}

def save_state(state: dict):
    Path(STATE_FILE).parent.mkdir(parents=True, exist_ok=True)
    Path(STATE_FILE).write_text(json.dumps(state, indent=2))

# ── Nginx config writer ────────────────────────────────────────────────────────
def write_upstream(node: str, ip: str, port: int):
    """Write /etc/nginx/conf.d/{node}_ip.conf as a set $variable file."""
    conf_path = Path(NGINX_CONF_DIR) / f"{node}_ip.conf"
    content = (
        f"# Auto-generated by ddns | node={node} | updated={datetime.utcnow().isoformat()}Z\n"
        f"set ${node}_ip {ip};\n"
    )
    conf_path.write_text(content)
    log.info(f"Wrote {conf_path}")

def reload_nginx() -> tuple[bool, str]:
    """Test config then reload nginx on the host."""
    # First test the config
    test = subprocess.run(
        ["nginx", "-t"],
        capture_output=True, text=True
    )
    if test.returncode != 0:
        err = test.stderr.strip()
        log.error(f"nginx -t failed: {err}")
        return False, err

    result = subprocess.run(
        NGINX_RELOAD.split(),
        capture_output=True, text=True
        shell=True
    )
    if result.returncode != 0:
        err = result.stderr.strip()
        log.error(f"nginx reload failed: {err}")
        return False, err

    log.info("nginx reloaded OK")
    return True, "ok"

# ── Auth ───────────────────────────────────────────────────────────────────────
def authorized(req) -> bool:
    auth = req.headers.get("Authorization", "")
    if auth.startswith("Bearer "):
        return auth[7:] == TOKEN
    # also accept token in JSON body or query param
    if req.is_json and req.json.get("token") == TOKEN:
        return True
    if req.args.get("token") == TOKEN:
        return True
    return False

def get_client_ip(req) -> str:
    # Trust CF-Connecting-IP if present (traffic comes through CF)
    for header in ("CF-Connecting-IP", "X-Real-IP", "X-Forwarded-For"):
        val = req.headers.get(header)
        if val:
            return val.split(",")[0].strip()
    return req.remote_addr

# ── Routes ─────────────────────────────────────────────────────────────────────
@app.get("/health")
def health():
    return jsonify({"status": "ok", "time": datetime.utcnow().isoformat() + "Z"})


@app.post("/update")
def update():
    if not authorized(request):
        log.warning(f"Unauthorized request from {request.remote_addr}")
        return jsonify({"error": "unauthorized"}), 401

    data = request.get_json(silent=True) or {}

    node = data.get("node", "").strip()
    if not node or not node.replace("-", "").replace("_", "").isalnum():
        return jsonify({"error": "node name required (alphanumeric, hyphens, underscores)"}), 400

    # IP: explicit override OR auto-detect from request source
    ip = data.get("ip") or get_client_ip(request)
    port = int(data.get("port", 80))

    state = load_state()
    old_ip = state.get(node, {}).get("ip")

    state[node] = {
        "ip":      ip,
        "port":    port,
        "updated": datetime.utcnow().isoformat() + "Z",
    }

    write_upstream(node, ip, port)
    save_state(state)

    ok, msg = reload_nginx()
    if not ok:
        return jsonify({
            "error":   "nginx reload failed",
            "detail":  msg,
            "node":    node,
            "ip":      ip,
        }), 500

    log.info(f"Updated node={node} ip={ip} port={port} (was {old_ip})")
    return jsonify({
        "status":  "ok",
        "node":    node,
        "ip":      ip,
        "port":    port,
        "changed": old_ip != ip,
        "old_ip":  old_ip,
    })


@app.get("/status")
def status():
    if not authorized(request):
        return jsonify({"error": "unauthorized"}), 401
    return jsonify(load_state())


@app.delete("/node/<node>")
def delete_node(node: str):
    if not authorized(request):
        return jsonify({"error": "unauthorized"}), 401

    state = load_state()
    if node not in state:
        return jsonify({"error": "node not found"}), 404

    # Remove upstream conf
    conf_path = Path(NGINX_CONF_DIR) / f"{node}_ip.conf"
    conf_path.unlink(missing_ok=True)

    del state[node]
    save_state(state)

    ok, msg = reload_nginx()
    if not ok:
        return jsonify({"error": "nginx reload failed", "detail": msg}), 500

    return jsonify({"status": "ok", "deleted": node})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=False)
